spring:
  aop:
   proxy-target-class: false 
dtx:
  aksds:
    mysql:
      maxIdleTime: 1000
      maxPoolSize: 1000
      minPoolSize: 10
      uniqueResourceName: mysqlXA
      xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
      xaProperties:
        URL: jdbc:mysql:///ntsp613db
        databaseName: ntsp613db
        password: root
        user: root
    ora:
      maxIdleTime: 1000
      maxPoolSize: 1000
      minPoolSize: 10
      uniqueResourceName: oraXA
      xaDataSourceClassName: oracle.jdbc.xa.client.OracleXADataSource
      xaProperties:
        URL: jdbc:oracle:thin:@localhost:1521:xe
        databaseName: xe
        password: manager
        user: system
